### ISSUE TITLE
Allow file uploads on tickets from user and agent/admin

### ISSUE THREAD

**Issue by gwmbox** [nanodesigns/nanosupport#108] opened 2021-07-02 04:48 UTC
Looking for an update for file attachments to tickets to be added to NanoSupport.

The ticket system is in need for being able to attach files to tickets from both user and agent/admin.  

Will need to include being able to choose what file types can be uploaded and the file size.

There is another issue ticket on this subject. but that is closed at https://github.com/nanodesigns/nanosupport/issues/4.  

Requests for this feature have been since 2016, It is now July 2021.  Is this going to be available anytime soon?

**Comment by mayeenulislam** [comment] 2021-07-02 20:07
At present no active development is happening in this plugin due to a lack of time, I'm afraid. But hopefully, sometime in the future, the feature will be added, inshaALLAH.

Duplicate of #4  Closing here.

**Closed by mayeenulislam** 2021-07-02 20:07 UTC
Labels: feature request
